package com.david.ProyectoSioca.serviceimp;

import java.io.File;

import javax.mail.internet.MimeMessage;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Component;
import org.springframework.util.ResourceUtils;

@Component
public class SendEmail {

	@Autowired
	private JavaMailSender sender;
	
	private String htmlEstructura;
	
	public void sendMail(String to,String subject,String body,String URLpdf) {
		MimeMessage message = sender.createMimeMessage();
		
		try {
			MimeMessageHelper mailMessage = new MimeMessageHelper(message,true);
			
			System.out.println("Estas en el try del envio del correo");
			File file = ResourceUtils.getFile(URLpdf);
			mailMessage.setFrom("david310702@gmail.com");
			mailMessage.setTo(to);
			mailMessage.setSubject(subject);
			mailMessage.setText(body);
			mailMessage.addAttachment("Orden de compra", file);
			sender.send(message);
		} catch (Exception e) {
			System.out.println(e);
		}
	}
	
	public void recuperarContraseñaEmail(String to,String codigo) {
		MimeMessage message = sender.createMimeMessage();
		try {
			MimeMessageHelper mailMessage = new MimeMessageHelper(message,true);
			
			this.htmlEstructura=String.join(System.getProperty("line.separator"), "<!DOCTYPE html>\r\n"
					+ "\r\n"
					+ "<html lang=\"en\" xmlns:o=\"urn:schemas-microsoft-com:office:office\" xmlns:v=\"urn:schemas-microsoft-com:vml\">\r\n"
					+ "\r\n"
					+ "<head>\r\n"
					+ "    <title></title>\r\n"
					+ "    <meta content=\"text/html; charset=utf-8\" http-equiv=\"Content-Type\" />\r\n"
					+ "    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\" />\r\n"
					+ "    <!--[if mso]><xml><o:OfficeDocumentSettings><o:PixelsPerInch>96</o:PixelsPerInch><o:AllowPNG/></o:OfficeDocumentSettings></xml><![endif]-->\r\n"
					+ "    <!--[if !mso]><!-->\r\n"
					+ "    <link href=\"https://fonts.googleapis.com/css?family=Montserrat\" rel=\"stylesheet\" type=\"text/css\" />\r\n"
					+ "    <!--<![endif]-->\r\n"
					+ "    <style>\r\n"
					+ "        * {\r\n"
					+ "            box-sizing: border-box;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        body {\r\n"
					+ "            margin: 0;\r\n"
					+ "            padding: 0;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        a[x-apple-data-detectors] {\r\n"
					+ "            color: inherit !important;\r\n"
					+ "            text-decoration: inherit !important;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        #MessageViewBody a {\r\n"
					+ "            color: inherit;\r\n"
					+ "            text-decoration: none;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        p {\r\n"
					+ "            line-height: inherit\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        .desktop_hide,\r\n"
					+ "        .desktop_hide table {\r\n"
					+ "            mso-hide: all;\r\n"
					+ "            display: none;\r\n"
					+ "            max-height: 0px;\r\n"
					+ "            overflow: hidden;\r\n"
					+ "        }\r\n"
					+ "\r\n"
					+ "        @media (max-width:620px) {\r\n"
					+ "\r\n"
					+ "            .desktop_hide table.icons-inner,\r\n"
					+ "            .social_block.desktop_hide .social-table {\r\n"
					+ "                display: inline-block !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .icons-inner {\r\n"
					+ "                text-align: center;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .icons-inner td {\r\n"
					+ "                margin: 0 auto;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .image_block img.big,\r\n"
					+ "            .row-content {\r\n"
					+ "                width: 100% !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .mobile_hide {\r\n"
					+ "                display: none;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .stack .column {\r\n"
					+ "                width: 100%;\r\n"
					+ "                display: block;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .mobile_hide {\r\n"
					+ "                min-height: 0;\r\n"
					+ "                max-height: 0;\r\n"
					+ "                max-width: 0;\r\n"
					+ "                overflow: hidden;\r\n"
					+ "                font-size: 0px;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .desktop_hide,\r\n"
					+ "            .desktop_hide table {\r\n"
					+ "                display: table !important;\r\n"
					+ "                max-height: none !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-5 .column-1 .block-1.paragraph_block td.pad>div,\r\n"
					+ "            .row-5 .column-1 .block-3.paragraph_block td.pad>div,\r\n"
					+ "            .row-7 .column-1 .block-4.paragraph_block td.pad>div,\r\n"
					+ "            .row-7 .column-2 .block-4.paragraph_block td.pad>div,\r\n"
					+ "            .row-8 .column-1 .block-4.paragraph_block td.pad>div,\r\n"
					+ "            .row-8 .column-2 .block-4.paragraph_block td.pad>div {\r\n"
					+ "                font-size: 16px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-5 .column-1 .block-2.paragraph_block td.pad>div,\r\n"
					+ "            .row-6 .column-1 .block-3.paragraph_block td.pad>div,\r\n"
					+ "            .row-9 .column-1 .block-2.paragraph_block td.pad>div {\r\n"
					+ "                font-size: 28px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-3 .column-1 .block-2.paragraph_block td.pad>div {\r\n"
					+ "                font-size: 76px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-3 .column-1 .block-1.paragraph_block td.pad>div {\r\n"
					+ "                font-size: 30px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-1 .column-1 .block-1.paragraph_block td.pad {\r\n"
					+ "                padding: 0 15px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-5 .column-1 .block-4.paragraph_block td.pad>div {\r\n"
					+ "                font-size: 12px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-6 .column-1 .block-2.paragraph_block td.pad>div,\r\n"
					+ "            .row-7 .column-1 .block-3.paragraph_block td.pad>div,\r\n"
					+ "            .row-7 .column-2 .block-3.paragraph_block td.pad>div,\r\n"
					+ "            .row-8 .column-1 .block-3.paragraph_block td.pad>div,\r\n"
					+ "            .row-8 .column-2 .block-3.paragraph_block td.pad>div {\r\n"
					+ "                font-size: 18px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-5 .column-1 {\r\n"
					+ "                padding: 25px 20px 30px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-8 .column-1 {\r\n"
					+ "                padding: 5px 0 20px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-14 .column-1 {\r\n"
					+ "                padding: 5px 30px !important;\r\n"
					+ "            }\r\n"
					+ "\r\n"
					+ "            .row-14 .column-2 {\r\n"
					+ "                padding: 5px 30px 20px !important;\r\n"
					+ "            }\r\n"
					+ "        }\r\n"
					+ "    </style>\r\n"
					+ "</head>\r\n"
					+ "\r\n"
					+ "<body style=\"background-color: #0c1312; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;\">\r\n"
					+ "    <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-2\" role=\"presentation\"\r\n"
					+ "        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
					+ "        <tbody>\r\n"
					+ "            <tr>\r\n"
					+ "                <td>\r\n"
					+ "                    <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\"\r\n"
					+ "                        role=\"presentation\"\r\n"
					+ "                        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; color: #000000; width: 600px;\" width=\"600\">\r\n"
					+ "                        <tbody>\r\n"
					+ "                            <tr>\r\n"
					+ "                                <td class=\"column column-1\"\r\n"
					+ "                                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 5px; padding-bottom: 5px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
					+ "                                    width=\"100%\">\r\n"
					+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-1\"\r\n"
					+ "                                        role=\"presentation\"\r\n"
					+ "                                        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word; margin-top: 10px; margin-bottom: 10px;\"\r\n"
					+ "                                        width=\"100%\">\r\n"
					+ "                                        <tr>\r\n"
					+ "                                            <td class=\"pad\">\r\n"
					+ "                                                <div\r\n"
					+ "                                                    style=\"color:#ffffff;direction:ltr;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:30px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:21.599999999999998px;\">\r\n"
					+ "                                                    <p style=\"margin: 0;\">Restablecimiento de contraseña SIOCA</p>\r\n"
					+ "                                                </div>\r\n"
					+ "                                            </td>\r\n"
					+ "                                        </tr>\r\n"
					+ "                                    </table>\r\n"
					+ "                                </td>\r\n"
					+ "                            </tr>\r\n"
					+ "                        </tbody>\r\n"
					+ "                    </table>\r\n"
					+ "                </td>\r\n"
					+ "            </tr>\r\n"
					+ "        </tbody>\r\n"
					+ "    </table>\r\n"
					+ "    <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row row-5\" role=\"presentation\"\r\n"
					+ "        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\" width=\"100%\">\r\n"
					+ "        <tbody>\r\n"
					+ "            <tr>\r\n"
					+ "                <td>\r\n"
					+ "                    <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"row-content stack\"\r\n"
					+ "                        role=\"presentation\"\r\n"
					+ "                        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; background-color: #151719; color: #000000; width: 600px;\"\r\n"
					+ "                        width=\"600\">\r\n"
					+ "                        <tbody>\r\n"
					+ "                            <tr>\r\n"
					+ "                                <td class=\"column column-1\"\r\n"
					+ "                                    style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; font-weight: 400; text-align: left; vertical-align: top; padding-top: 25px; padding-bottom: 30px; border-top: 0px; border-right: 0px; border-bottom: 0px; border-left: 0px;\"\r\n"
					+ "                                    width=\"100%\">\r\n"
					+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-2\"\r\n"
					+ "                                        role=\"presentation\"\r\n"
					+ "                                        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
					+ "                                        width=\"100%\">\r\n"
					+ "                                        <tr>\r\n"
					+ "                                            <td class=\"pad\" style=\"padding-bottom:5px;padding-top:5px;\">\r\n"
					+ "                                                <div\r\n"
					+ "                                                    style=\"color:#01dad0;direction:ltr;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:18px;font-weight:700;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:38.4px;\">\r\n"
					+ "                                                    <p style=\"margin: 0;\">Escuchamos que perdiste tu contraseña en nuestro sistema Sioca. ¡Aqui te vamos ayudar!</p>\r\n"
					+ "                                                </div>\r\n"
					+ "                                            </td>\r\n"
					+ "                                        </tr>\r\n"
					+ "                                    </table>\r\n"
					+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-3\"\r\n"
					+ "                                        role=\"presentation\"\r\n"
					+ "                                        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
					+ "                                        width=\"100%\">\r\n"
					+ "                                        <tr>\r\n"
					+ "                                            <td class=\"pad\">\r\n"
					+ "                                                <div\r\n"
					+ "                                                    style=\"color:#ffffff;direction:ltr;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:18px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:21.599999999999998px;\">\r\n"
					+ "                                                    <p style=\"margin: 0;\"></p>\r\n"
					+ "                                                </div>\r\n"
					+ "                                            </td>\r\n"
					+ "                                        </tr>\r\n"
					+ "                                    </table>\r\n"
					+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"button_block block-6\"\r\n"
					+ "                                        role=\"presentation\" style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt;\"\r\n"
					+ "                                        width=\"100%\">\r\n"
					+ "                                        <tr>\r\n"
					+ "                                            <td class=\"pad\" style=\"text-align:center;padding-top:30px;\">\r\n"
					+ "                                                <div align=\"center\" class=\"alignment\">\r\n"
					+ "                                                    <!--[if mso]><v:roundrect xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:w=\"urn:schemas-microsoft-com:office:word\" href=\"https://www.example.com/\" style=\"height:42px;width:120px;v-text-anchor:middle;\" arcsize=\"0%\" stroke=\"false\" fillcolor=\"#205057\"><w:anchorlock/><v:textbox inset=\"0px,0px,0px,0px\"><center style=\"color:#ffffff; font-family:Tahoma, sans-serif; font-size:16px\"><![endif]--><a\r\n"
					+ "                                                        \r\n"
					+ "                                                        style=\"text-decoration:none;display:inline-block;color:#ffffff;background-color:#205057;border-radius:0px;width:auto;border-top:0px solid transparent;font-weight:700;border-right:0px solid transparent;border-bottom:0px solid transparent;border-left:0px solid transparent;padding-top:5px;padding-bottom:5px;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;text-align:center;mso-border-alt:none;word-break:keep-all;\"\r\n"
					+ "                                                        target=\"_blank\"><span\r\n"
					+ "                                                            style=\"padding-left:20px;padding-right:20px;font-size:16px;display:inline-block;letter-spacing:normal;\"><span\r\n"
					+ "                                                                dir=\"ltr\"\r\n"
					+ "                                                                style=\"word-break: break-word; line-height: 32px;\">"+codigo +"</span></span></a>\r\n"
					+ "                                                    <!--[if mso]></center></v:textbox></v:roundrect><![endif]-->\r\n"
					+ "                                                </div>\r\n"
					+ "                                            </td>\r\n"
					+ "                                        </tr>\r\n"
					+ "                                    </table>\r\n"
					+ "\r\n"
					+ "                                    <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"paragraph_block block-4\"\r\n"
					+ "                                        role=\"presentation\"\r\n"
					+ "                                        style=\"mso-table-lspace: 0pt; mso-table-rspace: 0pt; word-break: break-word;\"\r\n"
					+ "                                        width=\"100%\">\r\n"
					+ "                                        <tr>\r\n"
					+ "                                            <td class=\"pad\" style=\"padding-bottom:5px;padding-top:5px;\">\r\n"
					+ "                                                <div\r\n"
					+ "                                                    style=\"color:#ffffff;direction:ltr;font-family:Montserrat, Trebuchet MS, Lucida Grande, Lucida Sans Unicode, Lucida Sans, Tahoma, sans-serif;font-size:12px;font-weight:400;letter-spacing:0px;line-height:120%;text-align:center;mso-line-height-alt:14.399999999999999px;\">\r\n"
					+ "                                                    <p style=\"margin: 0;\">Si no haz solicitado el restablecimiento de contraseña en nuestro sistema Sioca, por favor haz caso omiso a este correo.</p>\r\n"
					+ "                                                </div>\r\n"
					+ "                                            </td>\r\n"
					+ "                                        </tr>\r\n"
					+ "                                    </table>\r\n"
					+ "                                </td>\r\n"
					+ "                            </tr>\r\n"
					+ "                        </tbody>\r\n"
					+ "                    </table>\r\n"
					+ "                </td>\r\n"
					+ "            </tr>\r\n"
					+ "        </tbody>\r\n"
					+ "    </table>\r\n"
					+ "\r\n"
					+ "</body>\r\n"
					+ "\r\n"
					+ "</html>");
			mailMessage.setFrom("david310702@gmail.com");
			mailMessage.setTo(to);
			mailMessage.setSubject("Recuperar contraseña");
			mailMessage.setText(this.htmlEstructura,true);
			System.out.println("Apunto de enviar correo");
			sender.send(message);
		} catch (Exception e) {
			System.out.println(e);
		}
	}
}
